# F5TTS_v1_Base | E2TTS_Base
model = "F5TTS_v1_Base"
# ref_audio = "infer/examples/basic/your_ref.wav"
# If an empty "", transcribes the reference audio automatically.
ref_text = ""
# ref_audio_2 = "infer/examples/basic/your_ref_2.wav"
ref_text_2 = ""
gen_text = "巨大的建筑，总是由一木一石叠起来的，我们何妨做做这一木一石呢？我时常做些零碎事，就是为此。 "
# File with text to generate. Ignores the text above.
gen_file = ""
remove_silence = false
output_dir = "tests"
output_file = "infer_cli_basic.wav"
